config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root 'staticpages#top'
  resources :users, only: [:new, :create]
  resources :articles do
    resources :favorites, only: [:create, :destroy]
  end
  
  namespace :openai do
    get 'tests/', to: 'tests#generate_text'
    get 'tests/show', to: 'tests#show'
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  delete 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  def created_by?(user)
    return true if user_id == user.id
  end
  

  def self.ransackable_attributes(auth_object = nil)
    ["body","title"]
  end

  def favorited?(user, type)
    favorites.where(user_id: user.id, favorite_type: type).exists?
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :favorite_type, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :articles, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true, length: { maximum: 10 }
  validates :email, uniqueness: true, presence: true

  validates :password, length: { minimum: 8 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  add_flash_types :success, :danger, :alert, :notice

  private

  def not_authenticated
    redirect_to root_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :require_login

  def index
    @q = Article.ransack(params[:q])
    @articles = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(article_params)
    
    if @article.save
      redirect_to articles_path, notice: '投稿が完了しました'
    else
      flash.now[:danger] = '投稿に失敗しました'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = current_user.articles.find(params[:id])
  end

  def update
    @article = current_user.articles.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article)
    end
  end


  def destroy
    @article = current_user.articles.find(params[:id])
    @article.destroy!
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = current_user.favorites.new(article_id: params[:article_id], favorite_type: params[:type])
    if @favorite.save
      redirect_to article_path(params[:article_id])
    end
  end

  def destroy
    @favorite = current_user.favorites.find_by(article_id: params[:article_id], favorite_type: params[:type])
    if @favorite.destroy!
      redirect_to article_path(params[:article_id]), status: :see_other
    end
end
end

app/controllers/openai/tests_controller.rb
class Openai::TestsController < ApplicationController
        protect_from_forgery
      
        def show; end
      
        def generate_text
          @user_input = params[:user_input]
      
          if @user_input.present?
            client = OpenAI::Client.new
            response = client.chat(
              parameters: {
                model: "gpt-4o",
                messages: [
                  { role: "system", content: "あなたは優秀なエンジニアです。初心者エンジニアでもわかるように、userの質問に回答してください。
                  ユーザーから、「どんな技術記事を書きたいのか、一言で入力してください」という文言とその一言が送信されたら、その一言に合わせた内容のテンプレートを3~5項目で作成してください。
                  ユーザーから、「MiniitaBotがあなたの記事内容を確認します。確認して欲しい箇所をペーストして」という文言とともに、記事内容が送信されたら、内容の正確性・誤字脱字の添削をしてください。
                  ユーザーから、「その他」の内容とともに質問などが送られてきたら、その内容に正確に回答してください。
                  
                  " },
                  { role: "user", content: @user_input }
                ],
                # 生成するテキストの創造性やランダム性を制御するパラメータ。値が低いと、より決定論的な（予測可能な）応答を生成し、値が高いと、より多様で創造的な応答を生成する
                temperature: 0.2
              }
            )

            # digメソッドは、ネストされたハッシュや配列から値を安全に取得するための便利なメソッド。キーが存在しない場合でもエラーを出さずにnilを返すため、ネストが深いデータ構造を扱う際に役立つ。
            @generated_text = response.dig("choices", 0, "message", "content")
            render json:{text: @generated_text}
          end
        end
      end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  skip_before_action :require_login, only: [:top]

  def top
  end
end

app/controllers/usages_controller.rb
class UsagesController < ApplicationController
  skip_before_action :require_login, only: [:new]
  def new
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = login(params[:email], params[:password])
  end

  def create
    @user = login(params[:email], params[:password])
  
    if @user
      redirect_to articles_path, success: 'ログインしました'
    else
      flash[:error] = 'ログインに失敗しました'
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, notice: 'ログアウトしました'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, success: '新規登録が完了しました'
      # sorceryのオートログイン機能
      auto_login(@user)
    else
      
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title = "")
    base_ttitle = "Miniita_trial"
    if title.empty?
      base_ttitle
    else
       "#{title} | #{base_ttitle}"
    end
  end

    class HTMLwithCoderay < Redcarpet::Render::HTML
      def block_code(code, language)
        case language.to_s
        when 'rb'
          lang = 'ruby'
        when 'yml'
          lang = 'yaml'
        when ''
          # 空欄のままだと「Invalid id given:」エラー
          lang = 'md'
        else
          lang = language
        end
  
        CodeRay.scan(code, lang).div
      end
    end
  
    def markdown(text)
      html_render = HTMLwithCoderay.new(filter_html: true, hard_wrap: true)
      options = {
        autolink: true,  # URLやメールアドレスを自動的にリンクに変換、gyazo,通常のリンクテキスト対応
        space_after_headers: true, #見出し後の文字の大きさ変換。app/assets/stylesheets/redcarpet_custom.cssでCSS指定し、app/assets/config/manifest.jsとapp/views/layouts/application.html.erbで指定。
        fenced_code_blocks: true, #コードブロックで表示
        tables: true,
        hard_wrap: true, # 改行を <br> タグに変換
        lax_html_blocks: true, # HTMLブロックを緩やかに解析するオプション。区切り線は通常のredcarpetにも入っているが、マークダウンとHTMLの混在をスムーズに処理してくれる
        no_intra_emphasis: true, #語句の強調。「**強調**」で強調される。（**の後にスペースなし）
        strikethrough: true, # 打ち消し線（ストライクスルー）。「~~打ち消し線~~」で打ち消し線が入る
      }

      extensions = {
      fenced_code_blocks: true
    }

      markdown    = Redcarpet::Markdown.new(html_render, options)
      markdown.render(text)
    end
  end

app/views/articles/_favorite.html.erb
<div class= "flex justify-between mt-20 lg:justify-center lg:space-x-10">
  <% if @article.favorited?(current_user, :like_first) %>
    <div class="tooltip" data-tip="参考になった">
      <%= link_to article_favorite_path(@article.id, type: :like_first), data: { turbo_method: :delete }, class: "unlike-button-1" do %>
      <i class="bi bi-arrow-through-heart-fill"></i>
      <%= @article.favorites.where(favorite_type: 'like_first').count %>
  <% end %>
  <% else %>
      <%= link_to article_favorites_path(@article.id, type: :like_first), data: { turbo_method: :post }, class: "like-button-1" do %>
      <i class="bi bi-arrow-through-heart"></i>
      <%= @article.favorites.where(favorite_type: 'like_first').count %>
  <% end %>
  <% end %>

  <% if @article.favorited?(current_user, :like_second) %>
     <%= link_to article_favorite_path(@article.id, type: :like_second), data: { turbo_method: :delete }, class: "unlike-button-2" do %>
     <i class="bi bi-balloon-heart-fill"></i>
     <%= @article.favorites.where(favorite_type: 'like_second').count %>
  <% end %>
  <% else %>
     <%= link_to article_favorites_path(@article.id, type: :like_second), data: { turbo_method: :post }, class: "like-button-2" do %>
     <i class="bi bi-balloon-heart"></i>
     <%= @article.favorites.where(favorite_type: 'like_second').count %>
  <% end %>
<% end %>
</div>

app/views/articles/edit.html.erb
<% content_for :title, page_title("編集") %>
<div class= "bg-white">
<div class= "w-5/6 mx-auto max-w-screen-xl">
  <div class="text-xl flex justify-center h-screen w-full"> 
    <div class="w-full h-full flex flex-col">
      <%= form_with model: @article do |form| %>
        <%= form.label :title, "タイトル", class: "bg-white text-gray-600" %>
        <%= form.text_field :title, placeholder: 'タイトル', class: 'bg-white text-gray-600 textarea textarea-bordered mb-4 w-full'%>
        <br>
        <%= form.label :body, "本文", class: "bg-white text-gray-600"%>
        <%= form.text_area :body, placeholder: '本文', class: "textarea textarea-bordered w-full mb-4 h-full bg-white text-gray-600" %>
        <%= form.submit "投稿する", class: "mt-10 flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"%>
      <% end %>
    </div>
  </div>
</div>

<div class= "w-5/6 mx-auto max-w-screen-xl">
  <div class="absolute top-40 left-12 grid grid-cols-1">
   <div class="tooltip mb-5" data-tip="各種機能の使い方">
    <%= render 'shared/usage'%>
    </div>
  </div>
  
  <div class="absolute top-40 right-12 grid grid-cols-1">
    <div class="tooltip mb-5" data-tip="マークダウン記法">
      <%= render 'shared/markdown'%>
    </div>
    <div class="tooltip mb-5" data-tip="Miniita Bot">
      <%= render 'shared/miniitabot'%>
    </div>
    <div class="tooltip mb-5" data-tip="エラー解消法">
      <%= render 'shared/error_template'%>
    </div>
    <div class="tooltip mb-5" data-tip="新技術">
      <%= render 'shared/skill_template'%>
    </div>
    <div class="tooltip mb-5" data-tip="アプリ開発">
    <%= render 'shared/app_template'%>
    </div>
    <div class="tooltip mb-5" data-tip="tips集">
      <%= render 'shared/tips_template'%>
    </div>
  </div> 
</div>
</div>

app/views/articles/index.html.erb
<% content_for :title, page_title("一覧") %>
<div class= "bg-white">
<div class= "w-5/6 mx-auto max-w-screen-xl">
  <div class="text-lg flex justify-center">
    <%= search_form_for @q do |f| %>
    <%= f.search_field :title_cont, class: "text-black bg-white input input-bordered" %>
    <%= f.submit '検索', class: "text-gray-600 rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"%>
    <% end %>
  </div>

  <div class= "grid grid-cols-1 lg:grid-cols-3 gap-4 mt-6">
    <% if @articles.present? %>
      <% @articles.each do |article| %>
      <div class="p-4 border rounded-lg">
        <h2 class="text-xl mt-2 text-gray-600"><%= link_to article.title, article_path(article) %></h2> 
        <h3 class="text-sm text-gray-600">作成日：<%= l article.created_at, format: :long%></h3>
        <h3 class="text-sm text-gray-600"><%= article.user.name %></h3>
      </div>
    <% end %>
    <% else %>
      <p>投稿がありません</p>
    <% end %>
  </div>

  <div class = "flex justify-center">
    <%= paginate @articles %>
  </div>
</div>
</div>

app/views/articles/show.html.erb
<% content_for :title, page_title("詳細") %>
<div class="bg-white">
<div class= "w-5/6 mx-auto max-w-screen-xl">
  <div class=" bg-white text-gray-600 textarea textarea-bordered w-full h-full " >
    <h1 class="text-3xl mt-5 flex justify-center"><%= @article.title %></h1>
    <h2 class="text-base mt-5 flex justify-center"><%=l @article.created_at, format: :long %></h2>
    <h3 class="flex justify-center mt-10 bg-white"><%= markdown(@article.body).html_safe %></h3>
  </div>

  <div class= "flex justify-center gap-7 mb-10 mt-10">
    <% if @article.user == current_user %>
      <%=link_to '編集', edit_article_path(@article), class: "rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"%>
      <%=link_to '削除', article_path(@article), data: { turbo_method: :delete, turbo_confirm: '投稿を削除しますか？' }, class: "rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"%>
    <% end %>
  </div>
  <div class= "flex justify-center gap-7 text-xl">
    <%= render 'shared/favorite' %>
    <%= render 'shared/twitter' %>
  </div>
</div>
</div>

app/views/shared/_after_login_header.html.erb
<header class="bg-black">
  <nav class="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8" aria-label="Global">
    <div class="flex lg:flex-1 items-center">
      <%= link_to root_path do %>
        <%= image_tag "logo.jpeg", class: "card-img-top", width: "100", height:"100" %>
      <% end %>
    </div>
    <div class="lg:flex lg:gap-x-12 font-biz items-center">
      <%= link_to '記事を投稿', new_article_path, class: "text-sm font-semibold leading-6 text-slate-200" %>
      <%= link_to "記事を閲覧", articles_path, class: "text-sm font-semibold leading-6 text-slate-200" %>
    </div>
    <div class="lg:flex lg:flex-1 lg:justify-end font-biz items-center">
      <%= link_to 'ログアウト', :logout, data: { turbo_method: :delete }, class: 'text-sm font-semibold leading-6 text-slate-200' %>
    </div>
  </nav>
</header>

app/views/shared/_before_login_header.html.erb
<header class="bg-black">
  <nav class="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8" aria-label="Global">
    <div class="flex lg:flex-1">
      <%= link_to root_path do %>
        <%= image_tag "logo.jpeg", class: "card-img-top", width: "100", height:"100" %>
      <% end %>
    </div>
    <div class="lg:flex lg:gap-x-12 font-biz">
      <%=link_to "記事を閲覧", articles_path, class: "text-sm font-semibold leading-6 text-slate-200" %>
       <%= link_to '新規登録', new_user_path, class: "text-sm font-semibold leading-6 text-slate-200" %>
    </div>
    <div class="lg:flex lg:flex-1 lg:justify-end font-biz">
      <%= link_to 'ログイン', :login, class: 'text-sm font-semibold leading-6 text-slate-200' %>
    </div>
  </nav>
</header>

app/views/shared/_favorite.html.erb
<!-------------１つ目のいいねボタン------------->
<div class="tooltip" data-tip="参考になった！">
<% if logged_in? %>
  <% if @article.favorited?(current_user, :like_first) %>
      <%= link_to article_favorite_path(@article.id, type: :like_first), data: { turbo_method: :delete }, class: "unlike-button-1" do %>
        <i class="bi bi-arrow-through-heart-fill"></i>
        <%= @article.favorites.where(favorite_type: 'like_first').count %>
     <% end %>
  <% else %>
      <%= link_to article_favorites_path(@article.id, type: :like_first), data: { turbo_method: :post }, class: "like-button-1" do %>
        <i class="bi bi-arrow-through-heart"></i>
        <%= @article.favorites.where(favorite_type: 'like_first').count %>
      <% end %>
  <% end %>
<% else %>
    <%= link_to login_path, class: "like-button-1" do %>
      <i class="bi bi-arrow-through-heart"></i>
      <%= @article.favorites.where(favorite_type: 'like_first').count %>
    <% end %>
  <% end %>
</div>
<!-------------１つ目のいいねボタン------------->
<!-------------２つ目のいいねボタン------------->
<div class="tooltip" data-tip="学びが深まった">
<% if logged_in? %>
  <% if @article.favorited?(current_user, :like_second) %>
     <%= link_to article_favorite_path(@article.id, type: :like_second), data: { turbo_method: :delete }, class: "unlike-button-2" do %>
       <i class="bi bi-award-fill"></i>
       <%= @article.favorites.where(favorite_type: 'like_second').count %>
     <% end %>
  <% else %>
     <%= link_to article_favorites_path(@article.id, type: :like_second), data: { turbo_method: :post }, class: "like-button-2" do %>
       <i class="bi bi-award"></i>
       <%= @article.favorites.where(favorite_type: 'like_second').count %>
      <% end %>
  <% end %>
<% else %>
    <%= link_to login_path, class: "like-button-1" do %>
      <i class="bi bi-award"></i>
      <%= @article.favorites.where(favorite_type: 'like_second').count %>
    <% end %>
  <% end %>
  </div>
<!-------------２つ目のいいねボタン------------->
<!-------------３つ目のいいねボタン------------->
<div class="tooltip" data-tip="解説が丁寧">
<% if logged_in? %>
<% if @article.favorited?(current_user, :like_third) %>
     <%= link_to article_favorite_path(@article.id, type: :like_third), data: { turbo_method: :delete }, class: "unlike-button-2" do %>
       <i class="bi bi-arrow-through-heart-fill"></i>
       <%= @article.favorites.where(favorite_type: 'like_third').count %>
     <% end %>
  <% else %>
     <%= link_to article_favorites_path(@article.id, type: :like_third), data: { turbo_method: :post }, class: "like-button-2" do %>
       <i class="bi bi-arrow-through-heart"></i>
       <%= @article.favorites.where(favorite_type: 'like_third').count %>
      <% end %>
  <% end %>
  <% else %>
    <%= link_to login_path, class: "like-button-1" do %>
      <i class="bi bi-arrow-through-heart"></i>
      <%= @article.favorites.where(favorite_type: 'like_third').count %>
    <% end %>
  <% end %>
</div>
<!-------------３つ目のいいねボタン------------->
<!-------------４つ目のいいねボタン------------->
<div class="tooltip" data-tip="独自の視点！">
<% if logged_in? %>
<% if @article.favorited?(current_user, :like_forth) %>
     <%= link_to article_favorite_path(@article.id, type: :like_forth), data: { turbo_method: :delete }, class: "unlike-button-2" do %>
       <i class="bi bi-brightness-alt-high-fill"></i>
       <%= @article.favorites.where(favorite_type: 'like_forth').count %>
     <% end %>
  <% else %>
     <%= link_to article_favorites_path(@article.id, type: :like_forth), data: { turbo_method: :post }, class: "like-button-2" do %>
       <i class="bi bi-brightness-alt-high"></i>
       <%= @article.favorites.where(favorite_type: 'like_forth').count %>
      <% end %>
  <% end %>
  <% else %>
    <%= link_to login_path, class: "like-button-1" do %>
      <i class="bi bi-brightness-alt-high"></i>
      <%= @article.favorites.where(favorite_type: 'like_forth').count %>
    <% end %>
  <% end %>
</div>
<!-------------４つ目のいいねボタン------------->
<!-------------５つ目のいいねボタン------------->
<div class="tooltip" data-tip="詳細をもっと知りたい">
<% if logged_in? %>
<% if @article.favorited?(current_user, :like_fifth) %>
     <%= link_to article_favorite_path(@article.id, type: :like_fifth), data: { turbo_method: :delete }, class: "unlike-button-2" do %>
       <i class="bi bi-bell-fill"></i>
       <%= @article.favorites.where(favorite_type: 'like_fifth').count %>
     <% end %>
  <% else %>
     <%= link_to article_favorites_path(@article.id, type: :like_fifth), data: { turbo_method: :post }, class: "like-button-2" do %>
       <i class="bi bi-bell"></i>
       <%= @article.favorites.where(favorite_type: 'like_fifth').count %>
      <% end %>
  <% end %>
  <% else %>
    <%= link_to login_path, class: "like-button-1" do %>
      <i class="bi bi-bell"></i>
      <%= @article.favorites.where(favorite_type: 'like_fifth').count %>
    <% end %>
  <% end %>
</div>
<!-------------５つ目のいいねボタン------------->

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_miniitabot.html.erb
<!-- モーダルのボタン -->
<button class="text-4xl" onclick="my_modal_2.showModal()">
  <i class="bi bi-chat-left-heart"></i>
</button>

<!-- モーダルの内容 -->
<dialog id="my_modal_2" class="modal">
  <div class="modal-box mb-5 bg-white text-gray-600">
    <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2" onclick="my_modal_2.close()">✕</button>
    <h3 class="font-bold text-lg">Miniita Botで質問</h3>
    <p class="py-4">
      <!----------チャット画面の大枠------------------->
      <div class="flex flex-col items-center justify-center py-6 w-full h-full">
        <div class="max-w-4xl w-full space-y-8 h-full">
          <div id="conversation" class="space-y-4 p-4 rounded overflow-y-auto">
          </div>

          <!-- ドロップダウンメニューとテキスト入力 -->
          <form id="text_form" class="flex items-center px-2 py-1 border-t border-gray-200 bg-white">
            <select id="dropdown" class="px-3 py-2 border rounded border-gray-300 bg-white text-gray-600 mr-2">
              <option value="">選択してください</option>
              <option value="どんな技術記事を書きたいのか、一言で入力してください">テンプレート</option>
              <option value="MiniitaBotがあなたの記事内容を確認します。確認して欲しい箇所をペーストして">記事の内容</option>
              <option value="その他">その他</option>
            </select>
            <input type="text" placeholder="質問内容を入力してください" id="user_input" class="flex-1 px-3 py-2 border rounded border-gray-300 focus:border-blue-500 focus:outline-none focus:ring bg-white text-gray-600">
            <button id="button_post" class="px-4 py-2 bg-green-500 text-white rounded-md transition duration-300 ease-in-out hover:bg-green-600 focus:outline-none focus:ring focus:ring-green-200 ml-2">送信</button>
          </form>
        </div>
      </div>

      <script>
        const button_post = document.getElementById('button_post');
        const dropdown = document.getElementById('dropdown');
        const userInput = document.getElementById('user_input');

        // ドロップダウンメニューの選択が変更されたときの処理
        dropdown.addEventListener('change', function() {
          userInput.value = dropdown.value;
        });

        button_post.addEventListener('click', function(event) {
          event.preventDefault();

          if (userInput.value.trim() === "") {
            return;
          }

          const url = "<%= openai_tests_path('json') %>?user_input=" + userInput.value;
          const postOptions = {
            headers: {
              'Accept': 'application/json',
              'Content-Type': 'application/json'
            },
            method: "GET"
          };

          fetch(url, postOptions)
            .then(response => response.json())
            .then(item => {
              const list = document.getElementById("conversation");

              // ユーザーの質問
              const inputHTML = `
                <div class="text-right flex items-end justify-end space-x-2">
                  <div class="chat-bubble inline-block bg-blue-100 px-4 py-2 rounded-lg max-w-3/4 break-words text-sky-950">
                    <span>${userInput.value}</span>
                  </div>
                </div>`;
              list.insertAdjacentHTML("beforeend", inputHTML);

              // MiniitaBotからの返事
              const responseHTML = `
                <div class="text-left flex items-start space-x-2">
                  <div class="chat-bubble inline-block bg-gray-100 px-4 py-2 rounded-lg max-w-3/4 break-words text-sky-950">
                    <span>${item.text}</span>
                  </div>
                </div>`;
              list.insertAdjacentHTML("beforeend", responseHTML);
              userInput.value = "";
              list.scrollTop = list.scrollHeight;
            })
            .catch(error => console.error('Error:', error));
        });
      </script>
    </p>
  </div>
</dialog>

app/views/shared/_twitter.html.erb
<!-----margin-top: 5pxは、いいねボタンと高さを合わせるために記載------->
<%= link_to "https://twitter.com/intent/tweet?url=#{articles_url}&text=【Miniita_trial】に記事を投稿しました%0a%0a %23EverydayWithTechnicalArticles %23技術記事をもっと身近に %23Miniita_trial%0a%0a", 
:onclick=>"window.open(this.href,'hoge', 'height=480, width=640');return false;", target: '_blank', data: { toggle: "tooltip", placement: "bottom" }, title: "Xでシェアする", style: "display: inline-block; margin-top: 5px;" do %>
  <svg class="style-1b1cd5z" viewBox="0 0 20 20" style="width: 20px; height: 20px;">
    <path d="m11.68 8.62 6.55-7.62h-1.55l-5.69 6.62-4.55-6.62h-5.25l6.88 10.01-6.88 7.99h1.55l6.01-6.99 4.8 6.99h5.24l-7.13-10.38zm-2.13 2.47-.7-1-5.54-7.92h2.39l4.47 6.4.7 1 5.82 8.32h-2.39l-4.75-6.79z"></path>
  </svg>
<% end %>